service: kth-devops-api-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1
  stage: dev
  profile: Personal
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "*"

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 1

package:
  individually: true
  patterns:
    - '!**'

functions:
  # getUser:
  #   handler: get_user/get_user.lambda_handler
  #   events:
  #     - http:
  #         method: POST
  #         path: get_user
  #         cors:
  #           origin: '*'
  #           headers:
  #             - Content-Type
  #             - X-Amz-Date
  #             - Authorization
  #             - X-Api-Key
  #             - X-Amz-Security-Token
  #             - X-Amz-User-Agent
  #             - Cache-Control
  #             - Pragma
  #             - Expires
  #   package:
  #     patterns:
  #       - get_user/**
  addUser:
    handler: add_user/add_user.lambda_handler
    events:
      - http:
          method: POST
          path: /user/add_user
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Cache-Control
              - Pragma
              - Expires
    package:
      patterns:
        - add_user/**
