name: Demo Terraform Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Terraform Dev
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-north-1'
      AWS_PROFILE: Personal

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[Personal]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.9.5'

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/stages/dev

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform/stages/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/stages/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/stages/dev
