name: Demo Terraform Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  terraform:
    name: Deploy Terraform Dev
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-north-1'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.9.5'

    - name: Terraform Init
      run: terraform init
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Demo/terraform/stages/dev
