name: Demo Deploy Infrastructure Dev

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
    - name: Setup AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[Personal]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

  terraform:
    name: Deploy Terraform Dev
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.9.5'

    - name: Terraform Init
      run: terraform init
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./Demo/terraform/stages/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Demo/terraform/stages/dev

  deploy_serverless:
    name: Deploy Serverless Dev
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Serverless CLI
      run: npm install -g serverless

    - name: Deploy Serverless Application
      run: serverless deploy --stage dev
      working-directory: ./Demo/api
